class ModelConfig:
    BERT_MODEL = 'distilbert-base-uncased'
    MAX_LENGTH = 256 
    LSTM_UNITS = 156
    FEATURE_DIM = 64
    FUSION_LAYERS = [320, 160]
    DROPOUT_RATES = [0.25, 0.35]
    NUM_CLASSES = 3
    BATCH_SIZE = 32
    LEARNING_RATE = 1e-5
    DECAY_STEPS = 1000
    DECAY_RATE = 0.9
    EPOCHS = 10
    SHUFFLE_BUFFER_SIZE = 10000
    SAMPLES_PER_CLASS = 4000
    VALIDATION_SPLIT = 0.1
    EARLY_STOPPING_PATIENCE = 2
    LOSS = 'sparse_categorical_crossentropy'
    METRICS = ['accuracy']